version: "3" # docker-compose version 3

services:
  sartorius-server:
    container_name: sartorius-server
    image: teozz89/sartorius:detectron2
    ports:
      - "8081:8080"
      - "8082:8081"
      - "8083:8082"

  sartorius-ui:
    image: teozz89/sartorius_ui:latest
    ports:
      - "8501:8501"
    depends_on:
      # this will only start if the server is started sucessfully
      - sartorius-server
    
    links:
      - sartorius-server
    
